sudo: required
dist: trusty
language: node_js
branches:
  only:
    - master
    - develop
    - /\d+\.\d+\.\d+/

before_script:
  - npm install -g angular-cli
  - npm install -g karma
  - npm install -g npm
  - npm install

script:
  - npm run ci

notifications:
  email:
    on_success: never
    on_failure: never