language: node_js
branches:
  only:
    - master
    - develop
    - /\d+\.\d+\.\d+/

notifications:
  email:
    on_success: never
    on_failure: never

cache:
  directories:
    - node_modules
    - node

before_install:
  - npm install angular-cli@latest
  - npm install npm@latest
  - npm install nvm@latest
  - npm cache verify

install:
  - npm install

script:
  - ng build --prod