language: node_js
branches:
  only:
    - master
    - develop
    - /\d+\.\d+\.\d+/

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g angular-cli
  - npm install -g karma
  - npm install -g npm
  - npm install
  - ng build

install:
  - npm install

script:
  - ng build --prod

notifications:
  email:
    on_success: never
    on_failure: never