sudo: required
dist: trusty

language: node_js
branches:
  only:
    - master
    - develop
    - /\d+\.\d+\.\d+/

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - ng build --prod

notifications:
  email:
    on_success: never
    on_failure: never