language: node_js
branches:
  only:
    - master
    - develop
    - /\d+\.\d+\.\d+/

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install -g npm
- npm install

script:
- ng build --prod

notifications:
  email:
    on_success: never
    on_failure: never